- hosts: localhost
  connection: local

  vars:
    homebrew_packages:
      - name: ansible
      - name: tmux
      - name: hub

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'