- hosts: localhost
  connection: local

  vars:
    homebrew_packages:
      - name: ansible
      - name: tmux
      - name: hub
      - name: rbenv
      - name: ruby-build
      - name: openssl
      - name: readline
      - name: imagemagick
      - name: docker
      - name: go
      - name: yarn
      - name: ndenv
      - name: tree
      - name: starship
    homebrew_cask_packages:
      - name: google-chrome
      - name: simplenote
      - name: slack

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew packages install
      homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ homebrew_packages }}"

    - name: homebrew cask packages install
      homebrew_cask:
        name: "{{ item.name }}"
        state: present
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: "{{ homebrew_cask_packages }}"