- hosts: localhost
  connection: local

  vars:
    homebrew_taps:
      - caskroom/cask

    homebrew_packages:
      - name: ansible
      - name: tmux
      - name: hub
      - name: rbenv
      - name: ruby-build
      - name: openssl
      - name: readline
      - name: imagemagick
      - name: docker
      - name: go

    homebrew_cask_packages:
      # - name: google-chrome
      # - name: docker

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew tap
      homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_taps }}"

    - name: homebrew packages install
      homebrew:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ homebrew_packages }}"

    # - name: homebrew cask packages install
    #   homebrew_cask:
    #     name: "{{ item.name }}"
    #     state: "{{ item.state | default('present') }}"
    #   environment:
    #     HOMEBREW_CASK_OPTS: "--appdir=/Applications"
    #   with_items: "{{ homebrew_cask_packages }}"